-- MySQL Script generated by MySQL Workbench
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema investigacion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `investigacion` ;

-- -----------------------------------------------------
-- Schema investigacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `investigacion` DEFAULT CHARACTER SET utf8 ;
USE `investigacion` ;

-- -----------------------------------------------------
-- Table `investigacion`.`Autores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `investigacion`.`Autores` ;

CREATE TABLE IF NOT EXISTS `investigacion`.`Autores` (
  `ID` INT NOT NULL,
  `url` VARCHAR(45) NULL,
  `eid` VARCHAR(12) NULL,
  `document_count` INT NULL,
  `affiliation_name` VARCHAR(45) NULL,
  `affiliation_city` VARCHAR(20) NULL,
  `affiliation_contry` VARCHAR(20) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
